version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ${MINIO_DATA_DIR}:/data
    expose:
      - "9000"
      - "9001"
    networks:
      - minio_net

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/minio.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    depends_on:
      - minio
    ports:
      - "80:80"
      - "443:443"
    networks:
      - minio_net
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email
      -d ${DOMAIN} && echo 'Certificate acquired.'"

  cert-renew:
    image: certbot/certbot
    container_name: cert-renew
    volumes:
      - certbot-etc:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot --quiet &&
      nginx -s reload;
      sleep 12h;
      done"
    networks:
      - minio_net
    depends_on:
      - nginx
    restart: always

volumes:
  certbot-etc:
  certbot-web:

networks:
  minio_net:
